In [1]:
import pandas as pd
import numpy as np
import time
import glob
import duckdb
import statsbombpy as sb

In [2]:
# create a connection to an in-memory DuckDB database
con = duckdb.connect("../data/database/futbol-analysis.db")

In [3]:
# create competitions table from json file
con.execute("""
CREATE OR REPLACE TABLE competitions AS
    SELECT * FROM '../data/open-data-master/data/competitions.json';
""")

In [4]:

# create matches table from json files
con.execute("""
CREATE OR REPLACE TABLE matches AS
    SELECT * FROM '../data/open-data-master/data/matches/*/*.json';
""")

In [5]:

# create lineups table from json files
con.execute("""
CREATE OR REPLACE TABLE lineups AS
    SELECT * FROM '../data/open-data-master/data/lineups/*.json';
""")

In [6]:
# create events table from json files
con.execute("""
CREATE OR REPLACE TABLE events AS
    SELECT * FROM read_json(
        '../data/open-data-master/data/events/*.json',
        format='auto',
        union_by_name=true
    );
""")

In [7]:
# check the tables created and get their schema

print(con.execute("""
SHOW TABLES;
""").df())

competitions_table_info = con.execute("""
PRAGMA table_info('competitions');
""").df()

matches_table_info = con.execute("""
PRAGMA table_info('matches');
""").df()

lineups_table_info = con.execute("""
PRAGMA table_info('lineups');
""").df()

events_table_info = con.execute("""
PRAGMA table_info('events');
""").df()

           name
0  competitions
1        events
2       lineups
3       matches

In [8]:
competitions_table_info

    cid                       name     type  notnull dflt_value     pk
0     0             competition_id   BIGINT    False       None  False
1     1                  season_id   BIGINT    False       None  False
2     2               country_name  VARCHAR    False       None  False
3     3           competition_name  VARCHAR    False       None  False
4     4         competition_gender  VARCHAR    False       None  False
5     5          competition_youth  BOOLEAN    False       None  False
6     6  competition_international  BOOLEAN    False       None  False
7     7                season_name  VARCHAR    False       None  False
8     8              match_updated  VARCHAR    False       None  False
9     9          match_updated_360  VARCHAR    False       None  False
10   10        match_available_360  VARCHAR    False       None  False
11   11            match_available  VARCHAR    False       None  False

In [9]:
# set competition_id and season_id to primary key in competitions table
con.execute("""
ALTER TABLE competitions
ADD PRIMARY KEY (competition_id, season_id);
""")

In [10]:
matches_table_info

,cid,name,type,notnull,dflt_value,pk
0,0,match_id,BIGINT,False,None,False
1,1,match_date,DATE,False,None,False
2,2,kick_off,TIME,False,None,False
3,3,competition,"STRUCT(competition_id BIGINT, country_name VAR...",False,None,False
4,4,season,"STRUCT(season_id BIGINT, season_name VARCHAR)",False,None,False
5,5,home_team,"STRUCT(home_team_id BIGINT, home_team_name VAR...",False,None,False
6,6,away_team,"STRUCT(away_team_id BIGINT, away_team_name VAR...",False,None,False
7,7,home_score,BIGINT,False,None,False
8,8,away_score,BIGINT,False,None,False
9,9,match_status,VARCHAR,False,None,False
10,10,match_status_360,VARCHAR,False,None,False
11,11,last_updated,VARCHAR,False,None,False
12,12,last_updated_360,VARCHAR,False,None,False
13,13,metadata,"STRUCT(data_version VARCHAR, shot_fidelity_ver...",False,None,False
14,14,match_week,BIGINT,False,None,False
15,15,competition_stage,"STRUCT(id BIGINT, ""name"" VARCHAR)",False,None,False
16,16,stadium,"STRUCT(id BIGINT, ""name"" VARCHAR, country STRU...",False,None,False
17,17,referee,"STRUCT(id BIGINT, ""name"" VARCHAR, country STRU...",False,None,False

In [11]:
# set match_id to primary key in matches table
con.execute("""
ALTER TABLE matches
ADD PRIMARY KEY (match_id);
""")

In [12]:
lineups_table_info

,cid,name,type,notnull,dflt_value,pk
0,0,team_id,BIGINT,False,None,False
1,1,team_name,VARCHAR,False,None,False
2,2,lineup,"STRUCT(player_id BIGINT, player_name VARCHAR, ...",False,None,False

In [13]:
# examine lineup structure from lineups table
lineup_structure = con.execute("""
SELECT lineups
FROM lineups
LIMIT 1;
""").df().iloc[0,0]
lineup_structure

{'team_id': 217,
 'team_name': 'Barcelona',
 'lineup': [{'player_id': 3109,
   'player_name': 'Malcom Filipe Silva de Oliveira',
   'player_nickname': 'Malcom',
   'jersey_number': 14,
   'country': {'id': 31, 'name': 'Brazil'},
   'cards': [],
   'positions': []},
  {'player_id': 3501,
   'player_name': 'Philippe Coutinho Correia',
   'player_nickname': 'Philippe Coutinho',
   'jersey_number': 7,
   'country': {'id': 31, 'name': 'Brazil'},
   'cards': [],
   'positions': [{'position_id': 15,
     'position': 'Left Center Midfield',
     'from': '45:00',
     'to': '45:00',
     'from_period': 2,
     'to_period': 2,
     'start_reason': 'Tactical Shift',
     'end_reason': 'Substitution - On (Tactical)'},
    {'position_id': 2,
     'position': 'Right Back',
     'from': '45:00',
     'to': '76:14',
     'from_period': 2,
     'to_period': 2,
     'start_reason': 'Substitution - On (Tactical)',
     'end_reason': 'Tactical Shift'},
    {'position_id': 21,
     'position': 'Left Wing',
     'from': '76:14',
     'to': None,
     'from_period': 2,
     'to_period': None,
     'start_reason': 'Tactical Shift',
     'end_reason': 'Final Whistle'}]},
  {'player_id': 5203,
   'player_name': 'Sergio Busquets i Burgos',
   'player_nickname': 'Sergio Busquets',
   'jersey_number': 5,
   'country': {'id': 214, 'name': 'Spain'},
   'cards': [],
   'positions': [{'position_id': 9,
     'position': 'Right Defensive Midfield',
     'from': '00:00',
     'to': '45:00',
     'from_period': 1,
     'to_period': 2,
     'start_reason': 'Starting XI',
     'end_reason': 'Tactical Shift'},
    {'position_id': 10,
     'position': 'Center Defensive Midfield',
     'from': '45:00',
     'to': '84:13',
     'from_period': 2,
     'to_period': 2,
     'start_reason': 'Tactical Shift',
     'end_reason': 'Substitution - Off (Tactical)'}]},
  {'player_id': 5211,
   'player_name': 'Jordi Alba Ramos',
   'player_nickname': 'Jordi Alba',
   'jersey_number': 18,
   'country': {'id': 214, 'name': 'Spain'},
   'cards': [],
   'positions': [{'position_id': 6,
     'position': 'Left Back',
     'from': '00:00',
     'to': None,
     'from_period': 1,
     'to_period': None,
     'start_reason': 'Starting XI',
     'end_reason': 'Final Whistle'}]},
  {'player_id': 5213,
   'player_name': 'Gerard Piqué Bernabéu',
   'player_nickname': 'Gerard Piqué',
   'jersey_number': 3,
   'country': {'id': 214, 'name': 'Spain'},
   'cards': [],
   'positions': [{'position_id': 3,
     'position': 'Right Center Back',
     'from': '00:00',
     'to': None,
     'from_period': 1,
     'to_period': None,
     'start_reason': 'Starting XI',
     'end_reason': 'Final Whistle'}]},
  {'player_id': 5246,
   'player_name': 'Luis Alberto Suárez Díaz',
   'player_nickname': 'Luis Suárez',
   'jersey_number': 9,
   'country': {'id': 242, 'name': 'Uruguay'},
   'cards': [],
   'positions': [{'position_id': 22,
     'position': 'Right Center Forward',
     'from': '00:00',
     'to': '45:00',
     'from_period': 1,
     'to_period': 2,
     'start_reason': 'Starting XI',
     'end_reason': 'Tactical Shift'},
    {'position_id': 23,
     'position': 'Center Forward',
     'from': '45:00',
     'to': None,
     'from_period': 2,
     'to_period': None,
     'start_reason': 'Tactical Shift',
     'end_reason': 'Final Whistle'}]},
  {'player_id': 5470,
   'player_name': 'Ivan Rakitić',
   'player_nickname': None,
   'jersey_number': 4,
   'country': {'id': 56, 'name': 'Croatia'},
   'cards': [],
   'positions': [{'position_id': 11,
     'position': 'Left Defensive Midfield',
     'from': '00:00',
     'to': '45:00',
     'from_period': 1,
     'to_period': 2,
     'start_reason': 'Starting XI',
     'end_reason': 'Tactical Shift'},
    {'position_id': 13,
     'position': 'Right Center Midfield',
     'from': '45:00',
     'to': '84:15',
     'from_period': 2,
     'to_period': 2,
     'start_reason': 'Tactical Shift',
     'end_reason': 'Tactical Shift'},
    {'position_id': 10,
     'position': 'Center Defensive Midfield',
     'from': '84:15',
     'to': None,
     'from_period': 2,
     'to_period': None,
     'start_reason': 'Tactical Shift',
     'end_reason': 'Final Whistle'}]},
  {'player_id': 5477,
   'player_name': 'Ousmane Dembélé',
   'player_nickname': None,
   'jersey_number': 11,
   'country': {'id': 78, 'name': 'France'},
   'cards': [],
   'positions': [{'position_id': 16,
     'position': 'Left Midfield',
     'from': '00:00',
     'to': '45:00',
     'from_period': 1,
     'to_period': 2,
     'start_reason': 'Starting XI',
     'end_reason': 'Tactical Shift'},
    {'position_id': 21,
     'position': 'Left Wing',
     'from': '45:00',
     'to': '76:12',
     'from_period': 2,
     'to_period': 2,
     'start_reason': 'Tactical Shift',
     'end_reason': 'Substitution - Off (Tactical)'}]},
  {'player_id': 5492,
   'player_name': 'Samuel Yves Umtiti',
   'player_nickname': 'Samuel Umtiti',
   'jersey_number': 23,
   'country': {'id': 78, 'name': 'France'},
   'cards': [],
   'positions': [{'position_id': 5,
     'position': 'Left Center Back',
     'from': '00:00',
     'to': None,
     'from_period': 1,
     'to_period': None,
     'start_reason': 'Starting XI',
     'end_reason': 'Final Whistle'}]},
  {'player_id': 5503,
   'player_name': 'Lionel Andrés Messi Cuccittini',
   'player_nickname': 'Lionel Messi',
   'jersey_number': 10,
   'country': {'id': 11, 'name': 'Argentina'},
   'cards': [],
   'positions': [{'position_id': 24,
     'position': 'Left Center Forward',
     'from': '00:00',
     'to': '45:00',
     'from_period': 1,
     'to_period': 2,
     'start_reason': 'Starting XI',
     'end_reason': 'Tactical Shift'},
    {'position_id': 17,
     'position': 'Right Wing',
     'from': '45:00',
     'to': None,
     'from_period': 2,
     'to_period': None,
     'start_reason': 'Tactical Shift',
     'end_reason': 'Final Whistle'}]},
  {'player_id': 6374,
   'player_name': 'Nélson Cabral Semedo',
   'player_nickname': 'Nélson Semedo',
   'jersey_number': 2,
   'country': {'id': 183, 'name': 'Portugal'},
   'cards': [],
   'positions': [{'position_id': 2,
     'position': 'Right Back',
     'from': '00:00',
     'to': '45:00',
     'from_period': 1,
     'to_period': 2,
     'start_reason': 'Starting XI',
     'end_reason': 'Substitution - Off (Tactical)'}]},
  {'player_id': 6379,
   'player_name': 'Sergi Roberto Carnicer',
   'player_nickname': 'Sergi Roberto',
   'jersey_number': 20,
   'country': {'id': 214, 'name': 'Spain'},
   'cards': [],
   'positions': [{'position_id': 12,
     'position': 'Right Midfield',
     'from': '00:00',
     'to': '45:00',
     'from_period': 1,
     'to_period': 2,
     'start_reason': 'Starting XI',
     'end_reason': 'Tactical Shift'},
    {'position_id': 2,
     'position': 'Right Back',
     'from': '45:00',
     'to': None,
     'from_period': 2,
     'to_period': None,
     'start_reason': 'Tactical Shift',
     'end_reason': 'Final Whistle'}]},
  {'player_id': 6826,
   'player_name': 'Clément Lenglet',
   'player_nickname': None,
   'jersey_number': 15,
   'country': {'id': 78, 'name': 'France'},
   'cards': [],
   'positions': []},
  {'player_id': 6998,
   'player_name': 'Rafael Alcântara do Nascimento',
   'player_nickname': 'Rafinha',
   'jersey_number': 12,
   'country': {'id': 31, 'name': 'Brazil'},
   'cards': [],
   'positions': []},
  {'player_id': 8206,
   'player_name': 'Arturo Erasmo Vidal Pardo',
   'player_nickname': 'Arturo Vidal',
   'jersey_number': 22,
   'country': {'id': 45, 'name': 'Chile'},
   'cards': [],
   'positions': [{'position_id': 10,
     'position': 'Center Defensive Midfield',
     'from': '84:13',
     'to': '84:15',
     'from_period': 2,
     'to_period': 2,
     'start_reason': 'Substitution - On (Tactical)',
     'end_reason': 'Tactical Shift'},
    {'position_id': 13,
     'position': 'Right Center Midfield',
     'from': '84:15',
     'to': None,
     'from_period': 2,
     'to_period': None,
     'start_reason': 'Tactical Shift',
     'end_reason': 'Final Whistle'}]},
  {'player_id': 8652,
   'player_name': 'Jasper Cillessen',
   'player_nickname': None,
   'jersey_number': 13,
   'country': {'id': 160, 'name': 'Netherlands'},
   'cards': [],
   'positions': []},
  {'player_id': 11392,
   'player_name': 'Arthur Henrique Ramos de Oliveira Melo',
   'player_nickname': 'Arthur',
   'jersey_number': 8,
   'country': {'id': 31, 'name': 'Brazil'},
   'cards': [],
   'positions': [{'position_id': 21,
     'position': 'Left Wing',
     'from': '76:12',
     'to': '76:14',
     'from_period': 2,
     'to_period': 2,
     'start_reason': 'Substitution - On (Tactical)',
     'end_reason': 'Tactical Shift'},
    {'position_id': 15,
     'position': 'Left Center Midfield',
     'from': '76:14',
     'to': None,
     'from_period': 2,
     'to_period': None,
     'start_reason': 'Tactical Shift',
     'end_reason': 'Final Whistle'}]},
  {'player_id': 20055,
   'player_name': 'Marc-André ter Stegen',
   'player_nickname': 'Marc-André ter Stegen',
   'jersey_number': 1,
   'country': {'id': 85, 'name': 'Germany'},
   'cards': [],
   'positions': [{'position_id': 1,
     'position': 'Goalkeeper',
     'from': '00:00',
     'to': None,
     'from_period': 1,
     'to_period': None,
     'start_reason': 'Starting XI',
     'end_reason': 'Final Whistle'}]}]}

In [14]:
events_table_info

,cid,name,type,notnull,dflt_value,pk
0,0,id,UUID,False,None,False
1,1,index,BIGINT,False,None,False
2,2,period,BIGINT,False,None,False
3,3,timestamp,TIME,False,None,False
4,4,minute,BIGINT,False,None,False
5,5,second,BIGINT,False,None,False
6,6,type,"STRUCT(id BIGINT, ""name"" VARCHAR)",False,None,False
7,7,possession,BIGINT,False,None,False
8,8,possession_team,"STRUCT(id BIGINT, ""name"" VARCHAR)",False,None,False
9,9,play_pattern,"STRUCT(id BIGINT, ""name"" VARCHAR)",False,None,False
10,10,team,"STRUCT(id BIGINT, ""name"" VARCHAR)",False,None,False
11,11,duration,DOUBLE,False,None,False
12,12,tactics,"STRUCT(formation BIGINT, lineup STRUCT(player ...",False,None,False
13,13,related_events,UUID[],False,None,False
14,14,player,"STRUCT(id BIGINT, ""name"" VARCHAR)",False,None,False
15,15,position,"STRUCT(id BIGINT, ""name"" VARCHAR)",False,None,False
16,16,location,DOUBLE[],False,None,False
17,17,pass,"STRUCT(recipient STRUCT(id BIGINT, ""name"" VARC...",False,None,False
18,18,carry,STRUCT(end_location DOUBLE[]),False,None,False
19,19,ball_receipt,"STRUCT(outcome STRUCT(id BIGINT, ""name"" VARCHAR))",False,None,False
20,20,under_pressure,BOOLEAN,False,None,False
21,21,duel,"STRUCT(""type"" STRUCT(id BIGINT, ""name"" VARCHAR...",False,None,False
22,22,counterpress,BOOLEAN,False,None,False
23,23,interception,"STRUCT(outcome STRUCT(id BIGINT, ""name"" VARCHAR))",False,None,False
24,24,off_camera,BOOLEAN,False,None,False
25,25,ball_recovery,"STRUCT(recovery_failure BOOLEAN, offensive BOO...",False,None,False
26,26,shot,"STRUCT(statsbomb_xg DOUBLE, end_location DOUBL...",False,None,False
27,27,goalkeeper,"STRUCT(end_location DOUBLE[], ""type"" STRUCT(id...",False,None,False
28,28,clearance,"STRUCT(left_foot BOOLEAN, body_part STRUCT(id ...",False,None,False
29,29,block,"STRUCT(deflection BOOLEAN, offensive BOOLEAN, ...",False,None,False
30,30,dribble,"STRUCT(nutmeg BOOLEAN, outcome STRUCT(id BIGIN...",False,None,False
31,31,foul_committed,"STRUCT(offensive BOOLEAN, card STRUCT(id BIGIN...",False,None,False
32,32,foul_won,"STRUCT(defensive BOOLEAN, advantage BOOLEAN, p...",False,None,False
33,33,out,BOOLEAN,False,None,False
34,34,miscontrol,STRUCT(aerial_won BOOLEAN),False,None,False
35,35,bad_behaviour,"STRUCT(card STRUCT(id BIGINT, ""name"" VARCHAR))",False,None,False
36,36,substitution,"STRUCT(outcome STRUCT(id BIGINT, ""name"" VARCHA...",False,None,False
37,37,50_50,"STRUCT(outcome STRUCT(id BIGINT, ""name"" VARCHAR))",False,None,False
38,38,injury_stoppage,STRUCT(in_chain BOOLEAN),False,None,False
39,39,half_start,STRUCT(late_video_start BOOLEAN),False,None,False
40,40,player_off,STRUCT(permanent BOOLEAN),False,None,False
41,41,half_end,STRUCT(early_video_end BOOLEAN),False,None,False

In [15]:
# set id to primary key in events table
con.execute("""
ALTER TABLE events
ADD PRIMARY KEY (id);
""")